image:
  file: .devcontainer/Dockerfile
  context: .devcontainer

tasks:
  - init: 'export PATH=$PATH:/usr/local/clang+llvm-5.0.2-x86_64-linux-gnu-ubuntu-16.04/bin
    && git submodule init
    && git submodule update
    && ./autogen.sh
    && ./configure --enable-tracy --enable-tracy-capture
    && bear make
    && make check'
    command: 'echo "Welcome to the stellar-core Gitpod development environment."'

vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd@0.1.5:VVxg4kW5VbJUP3ysCuG3Fg==